// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtGPefZT5eHVasnfR0fesf8rcV0MPSRNs',
    appId: '1:809207343020:web:4a8f8403cb838bbac4bc09',
    messagingSenderId: '809207343020',
    projectId: 'my-demo-project-4eea1',
    authDomain: 'my-demo-project-4eea1.firebaseapp.com',
    storageBucket: 'my-demo-project-4eea1.appspot.com',
    measurementId: 'G-LQSXBFXE4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgvTY2Gp-enaOGev_bN0c3bclvhN7WQSM',
    appId: '1:809207343020:android:5dc76a80e5fce54dc4bc09',
    messagingSenderId: '809207343020',
    projectId: 'my-demo-project-4eea1',
    storageBucket: 'my-demo-project-4eea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcLSNAcXw9rpk2ee8mZ7OTRl447Y_Vhqo',
    appId: '1:809207343020:ios:ba7856052e6aae99c4bc09',
    messagingSenderId: '809207343020',
    projectId: 'my-demo-project-4eea1',
    storageBucket: 'my-demo-project-4eea1.appspot.com',
    iosClientId: '809207343020-hcu5grngfvic4nps5miq52g137hn31rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduEcommerceFb2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcLSNAcXw9rpk2ee8mZ7OTRl447Y_Vhqo',
    appId: '1:809207343020:ios:ba7856052e6aae99c4bc09',
    messagingSenderId: '809207343020',
    projectId: 'my-demo-project-4eea1',
    storageBucket: 'my-demo-project-4eea1.appspot.com',
    iosClientId: '809207343020-hcu5grngfvic4nps5miq52g137hn31rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduEcommerceFb2',
  );
}
